# Makefile for MCC
# Targets x86-64 Linux
# Compiler: Clang (used to bootstrap MCC)

TARGET := mcc
CC := clang

# 1. Standards & Safety (The strict parent)
CFLAGS  = -std=c23 -Wall -Wextra -Wpedantic -Werror 

# 2. Isolation (The hermitage)
CFLAGS += -ffreestanding -fno-builtin -nostdinc -undef 

# 3. Runtime Stripping (The "God Mode" extensions)
CFLAGS += -nostdlib -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables

# 4. Memory Model (The raw pointer access)
CFLAGS += -fno-strict-aliasing -fno-common

# 5. Debugging & Includes
CFLAGS += -g -Iinclude

# -nostdlib: Do NOT link standard startup files (crt1.o) or libc.
# -no-pie: Disable Position Independent Executable (simplifies address calculation for now)
LDFLAGS := -nostdlib -no-pie

# Directories
SRC_DIR := src
OBJ_DIR := build
INC_DIR := include
TEST_DIR := test

# Recursively find all .c and .S (Assembly) files
SRCS_C := $(shell find $(SRC_DIR) -name '*.c')
SRCS_S := $(shell find $(SRC_DIR) -name '*.S')

TESTS_C := $(SRCS_C:$(SRC_DIR)/%.c=$(TEST_DIR)/%.txt)

# Generate object file paths in build/ mirroring src/ structure
OBJS_C := $(SRCS_C:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)
OBJS_S := $(SRCS_S:$(SRC_DIR)/%.S=$(OBJ_DIR)/%.o)

# Combine all objects
OBJS := $(OBJS_C) $(OBJS_S)

# Main Target
$(TARGET): $(OBJS)
	@$(CC) $(OBJS) -o $@ $(LDFLAGS)

# Compile C Source to Objects
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Compile Assembly Source to Objects
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.S
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@

# Formatting
format:
	@find $(SRC_DIR) $(INC_DIR) -name '*.[ch]' | xargs clang-format -i

# Testing (Updated to pass the target binary itself if needed)
test: $(TESTS_C) $(TARGET)

$(TEST_DIR)/%.txt: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@./$(TARGET) $< > $@

# Clean
clean:
	@rm -rf $(OBJ_DIR) $(TARGET) $(TEST_DIR) 

# Include dependencies generated by Clang (for header updates)
-include $(OBJS_C:.o=.d)

.PHONY: format test clean
